ci:
  skip: [pip-compile]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        args:
          - "--check-untyped-defs"
          - "--ignore-missing-imports"
        additional_dependencies:
          - types-setuptools
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pep8-naming
          - "git+https://github.com/zer0-x/flake8-typehinting#egg=flake8-typehinting"
          - flake8-builtins
          - flake8-bugbear
          - flake8-comprehensions
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.12.2
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args:
          - --resolver=backtracking
          - --generate-hashes
          - requirements/requirements.in
        files: ^requirements/requirements.in$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args:
          - --resolver=backtracking
          - --generate-hashes
          - requirements/requirements-dev.in
        files: ^requirements/requirements-dev.in$
